name: Trigger new release
on: [push]

#  schedule:
#    - cron: '26 15 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: builderenv

    steps:
      - uses: actions/checkout@v2

      - name: Initialize python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install --pre github3.py

      - name: Run release script
        run: python builder.py
        env:
          GH_OATH_TOKEN: ${{ secrets.GH_OATH_TOKEN }}